" etc/vimrc loaded
if v:lang =~ "utf8$" || v:lang =~ "UTF-8$"
   set fileencodings=ucs-bom,utf-8,latin1
endif

set nocompatible	" Use Vim defaults (much better!)
set bs=indent,eol,start		" allow backspacing over everything in insert mode
"set ai			" always set autoindenting on
"set backup		" keep a backup file
set viminfo='20,\"50	" read/write a .viminfo file, don't store more
			" than 50 lines of registers
set history=50		" keep 50 lines of command line history
set ruler		" show the cursor position all the time

" Switch syntax highlighting on, when the terminal has colors
" Also switch on highlighting the last used search pattern.
if &t_Co > 2 || has("gui_running")
  syntax on
  set hlsearch
endif

if &term=="xterm"
     set t_Co=8
     set t_Sb=[4%dm
     set t_Sf=[3%dm
endif

" Don't wake up system with blinking cursor:
" http://www.linuxpowertop.org/known.php
let &guicursor = &guicursor . ",a:blinkon0"
" settings
set number relativenumber
highlight LineNr ctermfg=darkgreen
highlight CursorLineNr ctermfg=magenta
filetype plugin indent on
" cursor
let &t_SI = "\e[5 q"
let &t_EI = "\e[2 q"
let &t_SR = "\e[3 q"
" line cursor
" autocmd InsertEnter * set cursorline
" autocmd InsertLeave * set nocursorline
" split defaults and navigations
set splitright
set splitbelow
map <C-h> <C-w>h
map <C-j> <C-w>j
map <C-k> <C-w>k
map <C-l> <C-w>l
" wild mode autocomplete filenames
set wildmode=longest,list,full
set wildmenu
" plugins
call plug#begin()
" List your plugins here
Plug 'tpope/vim-sensible'
Plug 'ojroques/vim-oscyank', {'branch': 'main'}
Plug 'dense-analysis/ale'
call plug#end()
" disable on text change and enter
let g:ale_lint_on_text_changed = 'never'
let g:ale_lint_on_enter = 0
let g:ale_lint_on_save = 1
" use :ALEToggle only
" let g:ale_enabled = 0
" clipboard
nmap <leader>c <Plug>OSCYankOperator
nmap <leader>cc <leader>c_
vmap <leader>c <Plug>OSCYankVisual



